"""
file_server.py
--------------
Asynchronous HTTP file delivery server built on aiohttp.web.

Serves direct download links generated by Vid-to-Link:
- Delivers files directly to the browser / download manager without intermediate pages.
- Full HTTP Range support (RFC 7233) for resuming downloads and multi-connection
  download managers (IDM, ADM, aria2, curl -C, wget -c).
- Streams files via OS-level zero-copy sendfile / chunked asynchronous streaming
  (aiohttp.web.FileResponse) so handling files > 2GB never loads them into RAM.
- Enforces strict file expiration: returns HTTP 410 (Gone) or 404 (Not Found)
  when the admin-configured retention period has passed.
"""

from __future__ import annotations

import asyncio
import logging
import os
import time
from pathlib import Path
from typing import Optional
from urllib.parse import unquote

from aiohttp import web

import config
import database
import utils

logger = logging.getLogger(__name__)


async def handle_health(request: web.Request) -> web.Response:
    """Health check endpoint for Railway monitoring and uptime monitors."""
    return web.json_response(
        {
            "status": "healthy",
            "service": "Vid-to-Link",
            "version": config.APP_VERSION,
            "timestamp": int(time.time()),
        }
    )


async def handle_index(request: web.Request) -> web.Response:
    """Root landing page showing service info."""
    html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vid-to-Link Service</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background: #0f172a;
            color: #f8fafc;
            display: flex;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            margin: 0;
            padding: 20px;
            box-sizing: border-box;
        }
        .card {
            background: #1e293b;
            border: 1px solid #334155;
            border-radius: 16px;
            padding: 40px;
            max-width: 520px;
            width: 100%;
            text-align: center;
            box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.5), 0 8px 10px -6px rgba(0, 0, 0, 0.5);
        }
        .badge {
            display: inline-block;
            background: #0284c7;
            color: #f0f9ff;
            font-size: 12px;
            font-weight: 700;
            padding: 6px 14px;
            border-radius: 9999px;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            margin-bottom: 20px;
        }
        h1 {
            margin: 0 0 12px 0;
            font-size: 26px;
            color: #38bdf8;
        }
        p {
            color: #94a3b8;
            font-size: 15px;
            line-height: 1.6;
            margin: 0 0 16px 0;
        }
        .features {
            background: #0f172a;
            border-radius: 10px;
            padding: 16px 20px;
            text-align: left;
            margin-top: 24px;
            font-size: 14px;
        }
        .features ul {
            margin: 0;
            padding-left: 20px;
            color: #cbd5e1;
        }
        .features li {
            margin-bottom: 8px;
        }
        .features li:last-child {
            margin-bottom: 0;
        }
    </style>
</head>
<body>
    <div class="card">
        <div class="badge">Direct Download Engine</div>
        <h1>Vid-to-Link Server</h1>
        <p>This service provides high-speed, direct HTTP file delivery for the Vid-to-Link Telegram bot.</p>
        <p>Send a video link to the bot on Telegram to obtain an instant, resumable direct download link.</p>
        <div class="features">
            <ul>
                <li>🚀 True direct streaming (no third-party landing pages)</li>
                <li>⚡️ Full HTTP Range support (resumable downloads, IDM compatible)</li>
                <li>📦 Large file support (>2GB) without RAM exhaustion</li>
                <li>⏳ Automatic file expiration and cleanup</li>
            </ul>
        </div>
    </div>
</body>
</html>"""
    return web.Response(text=html, content_type="text/html")


async def handle_download(request: web.Request) -> web.StreamResponse:
    """
    Direct HTTP file download handler.
    URL pattern: /download/{token}/{filename}
    """
    token = request.match_info.get("token", "").strip()
    if not token:
        raise web.HTTPBadRequest(text="Missing file token.")

    # 1. Lookup link record in SQLite
    link = await database.get_file_link(token)
    if not link:
        return web.Response(
            text="404 Not Found: The requested download link was not found or is invalid.",
            status=404,
            content_type="text/plain",
            charset="utf-8",
        )

    # 2. Check expiration
    now = int(time.time())
    if link["is_deleted"] or link["expires_at"] <= now:
        return web.Response(
            text=(
                "410 Gone: This download link has expired.\n"
                "Downloaded files are automatically deleted from server storage "
                "once the configured retention window ends."
            ),
            status=410,
            content_type="text/plain",
            charset="utf-8",
        )

    # 3. Check physical file on disk
    file_path = Path(link["file_path"])
    if not file_path.exists() or not file_path.is_file():
        await database.mark_file_link_deleted(token)
        return web.Response(
            text="404 Not Found: The file is no longer available on the server.",
            status=404,
            content_type="text/plain",
            charset="utf-8",
        )

    # 4. Increment download counter
    try:
        await database.increment_link_download_count(token)
    except Exception as exc:
        logger.debug("Failed to increment download counter: %s", exc)

    # 5. Build direct download response
    safe_filename = link["file_name"] or file_path.name
    headers = {
        "Content-Disposition": f'attachment; filename="{safe_filename}"',
        "Accept-Ranges": "bytes",
        "Cache-Control": "no-cache, no-store, must-revalidate",
        "Pragma": "no-cache",
        "Expires": "0",
    }

    try:
        return web.FileResponse(path=file_path, headers=headers)
    except Exception as exc:
        logger.warning("Error serving file for token %s: %s", token, exc)
        raise


def create_web_app() -> web.Application:
    """Build and configure the aiohttp Application."""
    app = web.Application()
    app.router.add_get("/", handle_index)
    app.router.add_get("/health", handle_health)
    app.router.add_get("/download/{token}/{filename}", handle_download)
    return app


async def start_file_server() -> tuple[web.AppRunner, web.TCPSite]:
    """Start the HTTP file server on 0.0.0.0:$PORT."""
    app = create_web_app()
    runner = web.AppRunner(app)
    await runner.setup()

    port = config.PORT
    site = web.TCPSite(runner, host="0.0.0.0", port=port)
    await site.start()

    logger.info(
        "Direct HTTP file server started on 0.0.0.0:%d (Public URL: %s)",
        port,
        config.get_base_url(),
    )
    return runner, site


async def stop_file_server(runner: web.AppRunner) -> None:
    """Gracefully stop the HTTP server."""
    await runner.cleanup()
    logger.info("Direct HTTP file server stopped.")
